use super::*;
use std::{collections::VecDeque};

struct Mock { candidates:Result<Vec<StationCandidate>,Failure>, observations:VecDeque<Result<Observation,Failure>>, actions:Vec<Action>, reject:Option<Failure> }
impl FurnacePort for Mock {
 fn candidates<'a>(&'a mut self,_:&'a SmeltingPlan)->PortFuture<'a,Vec<StationCandidate>>{let v=self.candidates.clone();Box::pin(async move{v})}
 fn observe<'a>(&'a mut self)->PortFuture<'a,Observation>{let v=self.observations.pop_front().unwrap_or(Err(Failure::ProcessingInterrupted));Box::pin(async move{v})}
 fn act<'a>(&'a mut self,a:Action)->PortFuture<'a,()>{self.actions.push(a);let e=self.reject.take();Box::pin(async move{e.map_or(Ok(()),Err)})}
}
fn plan()->SmeltingPlan{SmeltingPlan{recipe_id:"minecraft:iron_ingot".into(),input:"minecraft:raw_iron".into(),output:"minecraft:iron_ingot".into(),operations:1,output_per_operation:1,cook_ticks:200,compatible:vec![StationKind::Furnace],fuel:Stack{item:"minecraft:coal".into(),count:1},fuel_burn_ticks:1600}}
fn candidate()->StationCandidate{StationCandidate{position:BlockPosition{x:1,y:64,z:2},kind:StationKind::Furnace,distance:2.,reachable:true,known_compatible:true}}
fn obs(input:u32,fuel:u32,output:u32,player_output:u32)->Observation{Observation{connected:true,alive:true,station_loaded:true,menu:Some(StationKind::Furnace),revision:1,inventory:InventoryView{revision:1,stacks:vec![Stack{item:"minecraft:raw_iron".into(),count:1},Stack{item:"minecraft:coal".into(),count:1},Stack{item:"minecraft:iron_ingot".into(),count:player_output}],free_capacity:64,protected:vec![]},contents:FurnaceContents{input:(input>0).then(||Stack{item:"minecraft:raw_iron".into(),count:input}),fuel:(fuel>0).then(||Stack{item:"minecraft:coal".into(),count:fuel}),output:(output>0).then(||Stack{item:"minecraft:iron_ingot".into(),count:output}),progress_ticks:0}}}
fn options()->ExecutionOptions{ExecutionOptions{allow_existing_input:true,use_existing_fuel:true,collect_on_cancel:true,close_on_cancel:true,allow_partial:true,wait_for_all:true,timeout:Duration::from_secs(1),observation_interval:Duration::from_millis(1),confirmation_timeout:Duration::from_millis(10),reopen_limit:1}}
async fn run(mock:&mut Mock,cancel:CancellationToken)->SmeltResult{FurnaceExecutor::default().execute(plan(),options(),cancel,mock).await}
fn mock(observations:Vec<Observation>)->Mock{Mock{candidates:Ok(vec![candidate()]),observations:observations.into_iter().map(Ok).collect(),actions:vec![],reject:None}}

#[test] fn ranks_compatible_reachable_stably(){let mut far=candidate();far.distance=5.;let mut near=candidate();near.position.x=0;near.distance=1.;assert_eq!(rank_stations(vec![far,near],&plan())[0].position.x,0)}
#[tokio::test] async fn mocked_progression_confirms_both_sides(){let mut m=mock(vec![obs(1,1,0,0),obs(1,1,1,0),obs(0,0,0,1)]);let r=run(&mut m,CancellationToken::new()).await;assert_eq!(r.outcome,Outcome::Completed);assert_eq!(r.output_collected,1);assert!(m.actions.iter().any(|a|matches!(a,Action::CollectOutput(_))))}
#[tokio::test] async fn no_station(){let mut m=mock(vec![]);m.candidates=Ok(vec![]);assert_eq!(run(&mut m,CancellationToken::new()).await.outcome,Outcome::Failed(Failure::NoCompatibleStation))}
#[tokio::test] async fn unreachable(){let mut m=mock(vec![]);m.candidates.as_mut().unwrap()[0].reachable=false;assert_eq!(run(&mut m,CancellationToken::new()).await.outcome,Outcome::Failed(Failure::StationUnreachable))}
#[tokio::test] async fn incompatible_contents(){let mut o=obs(1,1,0,0);o.contents.input.as_mut().unwrap().item="minecraft:potato".into();let mut m=mock(vec![o]);assert_eq!(run(&mut m,CancellationToken::new()).await.outcome,Outcome::Failed(Failure::IncompatibleContents))}
#[tokio::test] async fn missing_input(){let mut o=obs(0,1,0,0);o.inventory.stacks.retain(|s|s.item!="minecraft:raw_iron");let mut m=mock(vec![o]);assert_eq!(run(&mut m,CancellationToken::new()).await.outcome,Outcome::Failed(Failure::MissingInput))}
#[tokio::test] async fn missing_or_protected_fuel(){let mut o=obs(1,0,0,0);o.inventory.protected.push("minecraft:coal".into());let mut m=mock(vec![o]);assert_eq!(run(&mut m,CancellationToken::new()).await.outcome,Outcome::Failed(Failure::MissingFuel))}
#[tokio::test] async fn no_output_capacity(){let mut o=obs(1,1,1,0);o.inventory.free_capacity=0;let mut m=mock(vec![o]);assert_eq!(run(&mut m,CancellationToken::new()).await.outcome,Outcome::Failed(Failure::InsufficientInventorySpace))}
#[tokio::test] async fn unload_death_disconnect(){for (failure,mut o) in [(Failure::StationUnavailable,obs(1,1,0,0)),(Failure::Died,obs(1,1,0,0)),(Failure::Disconnected,obs(1,1,0,0))]{match failure{Failure::StationUnavailable=>o.station_loaded=false,Failure::Died=>o.alive=false,_=>o.connected=false};let mut m=mock(vec![o]);assert_eq!(run(&mut m,CancellationToken::new()).await.outcome,Outcome::Failed(failure));}}
#[tokio::test] async fn wrong_menu_has_bounded_reopen(){let mut a=obs(1,1,0,0);a.menu=None;let mut m=mock(vec![a.clone(),a]);assert_eq!(run(&mut m,CancellationToken::new()).await.outcome,Outcome::Failed(Failure::WrongMenu));assert_eq!(m.actions.iter().filter(|a|matches!(a,Action::Open(_))).count(),2)}
#[tokio::test] async fn rejected_click(){let mut m=mock(vec![obs(0,1,0,0)]);m.reject=Some(Failure::ChangedContents);assert_eq!(run(&mut m,CancellationToken::new()).await.outcome,Outcome::Failed(Failure::ChangedContents))}
#[tokio::test] async fn processing_interruption(){let mut m=mock(vec![obs(1,1,0,0)]);assert_eq!(run(&mut m,CancellationToken::new()).await.outcome,Outcome::Failed(Failure::ProcessingInterrupted))}
#[tokio::test] async fn cancellation_is_structured_and_closes(){let token=CancellationToken::new();token.cancel();let mut m=mock(vec![]);let r=run(&mut m,token).await;assert_eq!(r.outcome,Outcome::Failed(Failure::Cancelled));assert!(m.actions.iter().any(|a|matches!(a,Action::Close)))}
#[tokio::test] async fn timeout_is_bounded(){let mut m=mock((0..2000).map(|_|obs(1,1,0,0)).collect());let mut o=options();o.timeout=Duration::from_millis(3);let r=FurnaceExecutor::default().execute(plan(),o,CancellationToken::new(),&mut m).await;assert_eq!(r.outcome,Outcome::Failed(Failure::TimedOut))}
